#secrets.toml
ELASTIC_CLOUD_ID = "ac668387facb455d9201540f7bcdccf3:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDM5OGQ1NGMzMzZlZTQ0MGM5MGVjM2VjYmIwYjc0MWRjJGQ4NDgxNTA2MWM1NDQwYjA4YmE3NTAxMGQ1YzM3MGJl"
ELASTIC_API_KEY = "bDMyb29aRUJmbEtlQzJiSDlEc0M6U3h1Q2t2UEpUc3lxYnBnWUdXaWl0QQ=="
HUGGINGFACE_API_KEY = "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"
